// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tst:menu@0.1.0
//     tst:menu-distributor@0.1.0

package tst_menu_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

type MenuItem struct {
	Name        string
	Meal        string
	Description witTypes.Option[string]
	Ingredients []string
	// Components that handled this item, in order. Lets a caller see the
	// pipeline topology the Workload wired up.
	Trace []string
}
