// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0
//     h3:pipeline@0.1.0
//     h3:reader@0.1.0

package wit_exports

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"h3reader/export_h3_pipeline_query"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport [async-lift]h3:pipeline/query@0.1.0#get-by-key
func wasm_export_h3_pipeline_query_get_by_key(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
		witRuntime.Unpin()
		result := export_h3_pipeline_query.GetByKey(value, value0)
		var option int32
		var option3 uintptr
		var option4 uint32
		var option5 uintptr
		var option6 uint32
		var option7 float64
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()
			utf8 := unsafe.Pointer(unsafe.StringData((payload).H3Index))
			pinner.Pin(utf8)
			utf81 := unsafe.Pointer(unsafe.StringData((payload).Timestamp))
			pinner.Pin(utf81)

			option = int32(0)
			option3 = uintptr(utf8)
			option4 = uint32(len((payload).H3Index))
			option5 = uintptr(utf81)
			option6 = uint32(len((payload).Timestamp))
			option7 = (payload).Value
		case witTypes.ResultErr:
			payload := result.Err()
			utf82 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf82)

			option = int32(1)
			option3 = uintptr(utf82)
			option4 = uint32(len(payload))
			option5 = 0
			option6 = 0
			option7 = 0
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_query_get_by_key(option, option3, option4, option5, option6, option7)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/query@0.1.0#get-by-key
func wasm_export_callback_h3_pipeline_query_get_by_key(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/query@0.1.0 [task-return]get-by-key
func wasm_export_task_return_h3_pipeline_query_get_by_key(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 float64)

//go:wasmexport [async-lift]h3:pipeline/query@0.1.0#get-by-time
func wasm_export_h3_pipeline_query_get_by_time(arg0 uintptr, arg1 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		witRuntime.Unpin()
		result := export_h3_pipeline_query.GetByTime(value)
		var option int32
		var option3 uintptr
		var option4 uint32
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()
			slice := payload
			length := uint32(len(slice))
			result1 := witRuntime.Allocate(pinner, uintptr(length*(8+4*4)), 8)
			for index, element := range slice {
				base := unsafe.Add(result1, index*(8+4*4))
				utf8 := unsafe.Pointer(unsafe.StringData((element).H3Index))
				pinner.Pin(utf8)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).H3Index)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
				utf80 := unsafe.Pointer(unsafe.StringData((element).Timestamp))
				pinner.Pin(utf80)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Timestamp)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
				*(*float64)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = (element).Value

			}

			option = int32(0)
			option3 = uintptr(result1)
			option4 = length
		case witTypes.ResultErr:
			payload := result.Err()
			utf82 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf82)

			option = int32(1)
			option3 = uintptr(utf82)
			option4 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_query_get_by_time(option, option3, option4)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/query@0.1.0#get-by-time
func wasm_export_callback_h3_pipeline_query_get_by_time(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/query@0.1.0 [task-return]get-by-time
func wasm_export_task_return_h3_pipeline_query_get_by_time(arg0 int32, arg1 uintptr, arg2 uint32)
