// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tst:menu@0.1.0
//     tst:menu-ingester@0.1.0

package downstream

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/tst_menu_types"
)

type MenuItem = tst_menu_types.MenuItem

//go:wasmimport downstream process
func wasm_import_process(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Process(items []tst_menu_types.MenuItem) witTypes.Result[[]tst_menu_types.MenuItem, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	slice7 := items
	length9 := uint32(len(slice7))
	result8 := witRuntime.Allocate(pinner, uintptr(length9*(11*4)), 4)
	for index, element := range slice7 {
		base := unsafe.Add(result8, index*(11*4))
		utf8 := unsafe.Pointer(unsafe.StringData((element).Name))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
		utf80 := unsafe.Pointer(unsafe.StringData((element).Meal))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Meal)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf80)))

		switch (element).Description.Tag() {
		case witTypes.OptionNone:
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(0))

		case witTypes.OptionSome:
			payload := (element).Description.Some()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(1))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uintptr(uintptr(utf81)))

		default:
			panic("unreachable")
		}
		slice := (element).Ingredients
		length := uint32(len(slice))
		result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result, index*(2*4))
			utf82 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf82)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf82)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = uint32(uintptr(uintptr(result)))
		slice4 := (element).Trace
		length6 := uint32(len(slice4))
		result5 := witRuntime.Allocate(pinner, uintptr(length6*(2*4)), 4)
		for index, element := range slice4 {
			base := unsafe.Add(result5, index*(2*4))
			utf83 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf83)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf83)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = uint32(length6)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = uint32(uintptr(uintptr(result5)))

	}

	wasm_import_process(uintptr(result8), length9, returnArea)
	var result18 witTypes.Result[[]tst_menu_types.MenuItem, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result16 := make([]tst_menu_types.MenuItem, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(11*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))))

				option = witTypes.Some[string](value11)
			default:
				panic("unreachable")
			}
			result13 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))))), index*(2*4))
				value12 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

				result13 = append(result13, value12)
			}

			result15 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))))), index*(2*4))
				value14 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

				result15 = append(result15, value14)
			}

			result16 = append(result16, tst_menu_types.MenuItem{Name: value, Meal: value10, Description: option, Ingredients: result13, Trace: result15})
		}

		result18 = witTypes.Ok[[]tst_menu_types.MenuItem, string](result16)
	case 1:
		value17 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result18 = witTypes.Err[[]tst_menu_types.MenuItem, string](value17)
	default:
		panic("unreachable")
	}
	result19 := result18
	return result19

}
