// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0
//     h3:pipeline@0.1.0
//     h3:distribute-gateway@0.1.0

package h3_pipeline_query

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"h3distgw/h3_pipeline_types"
	"runtime"
	"unsafe"
)

//go:wasmimport h3:pipeline/query@0.1.0 [stream-new-0]get-by-time
func wasm_stream_new_u8() uint64

//go:wasmimport h3:pipeline/query@0.1.0 [async-lower][stream-read-0]get-by-time
func wasm_stream_read_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport h3:pipeline/query@0.1.0 [async-lower][stream-write-0]get-by-time
func wasm_stream_write_u8(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport h3:pipeline/query@0.1.0 [stream-drop-readable-0]get-by-time
func wasm_stream_drop_readable_u8(handle int32)

//go:wasmimport h3:pipeline/query@0.1.0 [stream-drop-writable-0]get-by-time
func wasm_stream_drop_writable_u8(handle int32)

var wasm_stream_vtable_u8 = witTypes.StreamVtable[uint8]{
	1,
	1,
	wasm_stream_read_u8,
	wasm_stream_write_u8,
	nil,
	nil,
	wasm_stream_drop_readable_u8,
	wasm_stream_drop_writable_u8,
	nil,
	nil,
}

func MakeStreamU8() (*witTypes.StreamWriter[uint8], *witTypes.StreamReader[uint8]) {
	pair := wasm_stream_new_u8()
	return witTypes.MakeStreamWriter[uint8](&wasm_stream_vtable_u8, int32(pair>>32)),
		witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, int32(pair&0xFFFFFFFF))
}

func LiftStreamU8(handle int32) *witTypes.StreamReader[uint8] {
	return witTypes.MakeStreamReader[uint8](&wasm_stream_vtable_u8, handle)
}

type DataPoint = h3_pipeline_types.DataPoint

//go:wasmimport h3:pipeline/query@0.1.0 [async-lower]get-by-key
func wasm_import_get_by_key(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func GetByKey(h3Index string, timestamp string) witTypes.Result[h3_pipeline_types.DataPoint, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 4*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(h3Index))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(timestamp))
	pinner.Pin(utf80)

	witAsync.SubtaskWait(uint32(wasm_import_get_by_key(uintptr(utf8), uint32(len(h3Index)), uintptr(utf80), uint32(len(timestamp)), returnArea)))
	var result witTypes.Result[h3_pipeline_types.DataPoint, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 3*4))))

		result = witTypes.Ok[h3_pipeline_types.DataPoint, string](h3_pipeline_types.DataPoint{value, value1, *(*float64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))})
	case 1:
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))

		result = witTypes.Err[h3_pipeline_types.DataPoint, string](value2)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport h3:pipeline/query@0.1.0 [async-lower]get-by-time
func wasm_import_get_by_time(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func GetByTime(timestamp string) witTypes.Result[*witTypes.StreamReader[uint8], string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(timestamp))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_get_by_time(uintptr(utf8), uint32(len(timestamp)), returnArea)))
	var result witTypes.Result[*witTypes.StreamReader[uint8], string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*witTypes.StreamReader[uint8], string](LiftStreamU8(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[*witTypes.StreamReader[uint8], string](value)
	default:
		panic("unreachable")
	}

	return result

}
