// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tst:menu@0.1.0
//     tst:meal-gen@0.1.0

package tst_menu_stage

import (
	"wit_component/tst_menu_types"
)

type MenuItem = tst_menu_types.MenuItem
