// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0
//     h3:pipeline@0.1.0
//     h3:persister@0.1.0

package wit_exports

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"h3persister/export_h3_pipeline_persist"
	"h3persister/h3_pipeline_types"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport [async-lift]h3:pipeline/persist@0.1.0#persist-batch
func wasm_export_h3_pipeline_persist_persist_batch(arg0 uintptr, arg1 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := make([]h3_pipeline_types.DataPoint, 0, arg1)
		for index := 0; index < int(arg1); index++ {
			base := unsafe.Add(unsafe.Pointer(arg0), index*(8+4*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, h3_pipeline_types.DataPoint{value, value0, *(*float64)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))})
		}

		witRuntime.Unpin()
		result1 := export_h3_pipeline_persist.PersistBatch(result)
		var option int32
		var option2 uintptr
		var option3 uint32
		switch result1.Tag() {
		case witTypes.ResultOk:
			payload := result1.Ok()

			option = int32(0)
			option2 = uintptr(int32(payload))
			option3 = 0
		case witTypes.ResultErr:
			payload := result1.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option2 = uintptr(utf8)
			option3 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_persist_persist_batch(option, option2, option3)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/persist@0.1.0#persist-batch
func wasm_export_callback_h3_pipeline_persist_persist_batch(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/persist@0.1.0 [task-return]persist-batch
func wasm_export_task_return_h3_pipeline_persist_persist_batch(arg0 int32, arg1 uintptr, arg2 uint32)
