// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tst:menu@0.1.0
//     tst:menu-ingester@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

// Unused, but present to make the compiler happy
func main() {}
