// Generated by `wit-bindgen` 0.61.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tst:menu@0.1.0
//     tst:menu-distributor@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_tst_menu_stage"
	"wit_component/tst_menu_types"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (3 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport tst:menu/stage@0.1.0#process
func wasm_export_tst_menu_stage_process(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	result5 := make([]tst_menu_types.MenuItem, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(11*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))
		var option witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))) {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))))

			option = witTypes.Some[string](value1)
		default:
			panic("unreachable")
		}
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))))), index*(2*4))
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value2)
		}

		result4 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))))), index*(2*4))
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result4 = append(result4, value3)
		}

		result5 = append(result5, tst_menu_types.MenuItem{Name: value, Meal: value0, Description: option, Ingredients: result, Trace: result4})
	}

	witRuntime.Unpin()
	result6 := export_tst_menu_stage.Process(result5)

	switch result6.Tag() {
	case witTypes.ResultOk:
		payload := result6.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		slice15 := payload
		length17 := uint32(len(slice15))
		result16 := witRuntime.Allocate(pinner, uintptr(length17*(11*4)), 4)
		for index, element := range slice15 {
			base := unsafe.Add(result16, index*(11*4))
			utf8 := unsafe.Pointer(unsafe.StringData((element).Name))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
			utf87 := unsafe.Pointer(unsafe.StringData((element).Meal))
			pinner.Pin(utf87)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Meal)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf87)))

			switch (element).Description.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).Description.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(1))
				utf88 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf88)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uintptr(uintptr(utf88)))

			default:
				panic("unreachable")
			}
			slice := (element).Ingredients
			length := uint32(len(slice))
			result10 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
			for index, element := range slice {
				base := unsafe.Add(result10, index*(2*4))
				utf89 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf89)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf89)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))) = uint32(length)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = uint32(uintptr(uintptr(result10)))
			slice12 := (element).Trace
			length14 := uint32(len(slice12))
			result13 := witRuntime.Allocate(pinner, uintptr(length14*(2*4)), 4)
			for index, element := range slice12 {
				base := unsafe.Add(result13, index*(2*4))
				utf811 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf811)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf811)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = uint32(length14)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = uint32(uintptr(uintptr(result13)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(length17)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(result16)))

	case witTypes.ResultErr:
		payload := result6.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf818 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf818)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf818)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_tst:menu/stage@0.1.0#process
func wasm_export_post_return_tst_menu_stage_process(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
