// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0
//     h3:pipeline@0.1.0
//     h3:ingest-gateway@0.1.0

package h3_pipeline_ingest

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"h3ingestgw/h3_pipeline_types"
	"runtime"
	"unsafe"
)

type DataPoint = h3_pipeline_types.DataPoint

//go:wasmimport h3:pipeline/ingest@0.1.0 [async-lower]ingest-batch
func wasm_import_ingest_batch(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func IngestBatch(points []h3_pipeline_types.DataPoint) witTypes.Result[uint32, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	slice := points
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(8+4*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+4*4))
		utf8 := unsafe.Pointer(unsafe.StringData((element).H3Index))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).H3Index)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
		utf80 := unsafe.Pointer(unsafe.StringData((element).Timestamp))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).Timestamp)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
		*(*float64)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = (element).Value

	}

	witAsync.SubtaskWait(uint32(wasm_import_ingest_batch(uintptr(result), length, returnArea)))
	var result1 witTypes.Result[uint32, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result1 = witTypes.Ok[uint32, string](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result1 = witTypes.Err[uint32, string](value)
	default:
		panic("unreachable")
	}

	return result1

}

//go:wasmimport h3:pipeline/ingest@0.1.0 [async-lower]delete-by-key
func wasm_import_delete_by_key(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr) int32

func DeleteByKey(h3Index string, timestamp string) witTypes.Result[witTypes.Unit, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(h3Index))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(timestamp))
	pinner.Pin(utf80)

	witAsync.SubtaskWait(uint32(wasm_import_delete_by_key(uintptr(utf8), uint32(len(h3Index)), uintptr(utf80), uint32(len(timestamp)), returnArea)))
	var result witTypes.Result[witTypes.Unit, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, string](witTypes.Unit{})
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[witTypes.Unit, string](value)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport h3:pipeline/ingest@0.1.0 [async-lower]delete-by-time
func wasm_import_delete_by_time(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func DeleteByTime(timestamp string) witTypes.Result[uint32, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(timestamp))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_delete_by_time(uintptr(utf8), uint32(len(timestamp)), returnArea)))
	var result witTypes.Result[uint32, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint32, string](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[uint32, string](value)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport h3:pipeline/ingest@0.1.0 [async-lower]delete-all
func wasm_import_delete_all(arg0 uintptr) int32

func DeleteAll() witTypes.Result[uint32, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))

	witAsync.SubtaskWait(uint32(wasm_import_delete_all(returnArea)))
	var result witTypes.Result[uint32, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint32, string](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Err[uint32, string](value)
	default:
		panic("unreachable")
	}

	return result

}
