// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0
//     wasmcloud:blobstore@0.1.0
//     wasmcloud:secrets@2.1.0
//     wasmcloud:keyvalue@0.2.0
//     wasmcloud:messaging@0.3.0
//     wasmcloud:postgres@0.2.0
//     wasmcloud:nats@0.1.0
//     wasmcloud:component-go@0.2.0
//     h3:pipeline@0.1.0
//     h3:ingester@0.1.0

package wit_exports

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"h3ingester/export_h3_pipeline_ingest"
	"h3ingester/export_wasmcloud_nats_core_handler"
	"h3ingester/h3_pipeline_types"
	"h3ingester/wasmcloud_nats_types"
	"runtime"
	"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport [async-lift]h3:pipeline/ingest@0.1.0#ingest-batch
func wasm_export_h3_pipeline_ingest_ingest_batch(arg0 uintptr, arg1 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := make([]h3_pipeline_types.DataPoint, 0, arg1)
		for index := 0; index < int(arg1); index++ {
			base := unsafe.Add(unsafe.Pointer(arg0), index*(8+4*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, h3_pipeline_types.DataPoint{value, value0, *(*float64)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))})
		}

		witRuntime.Unpin()
		result1 := export_h3_pipeline_ingest.IngestBatch(result)
		var option int32
		var option2 uintptr
		var option3 uint32
		switch result1.Tag() {
		case witTypes.ResultOk:
			payload := result1.Ok()

			option = int32(0)
			option2 = uintptr(int32(payload))
			option3 = 0
		case witTypes.ResultErr:
			payload := result1.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option2 = uintptr(utf8)
			option3 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_ingest_ingest_batch(option, option2, option3)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/ingest@0.1.0#ingest-batch
func wasm_export_callback_h3_pipeline_ingest_ingest_batch(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/ingest@0.1.0 [task-return]ingest-batch
func wasm_export_task_return_h3_pipeline_ingest_ingest_batch(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]h3:pipeline/ingest@0.1.0#delete-by-key
func wasm_export_h3_pipeline_ingest_delete_by_key(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		value0 := unsafe.String((*uint8)(unsafe.Pointer(arg2)), arg3)
		witRuntime.Unpin()
		result := export_h3_pipeline_ingest.DeleteByKey(value, value0)
		var option int32
		var option1 uintptr
		var option2 uint32
		switch result.Tag() {
		case witTypes.ResultOk:

			option = int32(0)
			option1 = 0
			option2 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option1 = uintptr(utf8)
			option2 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_ingest_delete_by_key(option, option1, option2)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/ingest@0.1.0#delete-by-key
func wasm_export_callback_h3_pipeline_ingest_delete_by_key(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/ingest@0.1.0 [task-return]delete-by-key
func wasm_export_task_return_h3_pipeline_ingest_delete_by_key(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]h3:pipeline/ingest@0.1.0#delete-by-time
func wasm_export_h3_pipeline_ingest_delete_by_time(arg0 uintptr, arg1 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		witRuntime.Unpin()
		result := export_h3_pipeline_ingest.DeleteByTime(value)
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()

			option = int32(0)
			option0 = uintptr(int32(payload))
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_ingest_delete_by_time(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/ingest@0.1.0#delete-by-time
func wasm_export_callback_h3_pipeline_ingest_delete_by_time(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/ingest@0.1.0 [task-return]delete-by-time
func wasm_export_task_return_h3_pipeline_ingest_delete_by_time(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]h3:pipeline/ingest@0.1.0#delete-all
func wasm_export_h3_pipeline_ingest_delete_all() int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		result := export_h3_pipeline_ingest.DeleteAll()
		var option int32
		var option0 uintptr
		var option1 uint32
		switch result.Tag() {
		case witTypes.ResultOk:
			payload := result.Ok()

			option = int32(0)
			option0 = uintptr(int32(payload))
			option1 = 0
		case witTypes.ResultErr:
			payload := result.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option = int32(1)
			option0 = uintptr(utf8)
			option1 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_h3_pipeline_ingest_delete_all(option, option0, option1)

	}))
}

//go:wasmexport [callback][async-lift]h3:pipeline/ingest@0.1.0#delete-all
func wasm_export_callback_h3_pipeline_ingest_delete_all(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]h3:pipeline/ingest@0.1.0 [task-return]delete-all
func wasm_export_task_return_h3_pipeline_ingest_delete_all(arg0 int32, arg1 uintptr, arg2 uint32)

//go:wasmexport [async-lift]wasmcloud:nats/core-handler@0.1.0#handle-message
func wasm_export_wasmcloud_nats_core_handler_handle_message(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 uintptr, arg6 uint32, arg7 int32, arg8 uintptr, arg9 uint32) int32 {
	return int32(witAsync.Run(func() {
		pinner := &runtime.Pinner{}
		defer pinner.Unpin()
		value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
		value0 := unsafe.Slice((*uint8)(unsafe.Pointer(arg2)), arg3)
		var option witTypes.Option[string]
		switch arg4 {
		case 0:

			option = witTypes.None[string]()
		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(arg5)), arg6)

			option = witTypes.Some[string](value1)
		default:
			panic("unreachable")
		}
		var option4 witTypes.Option[[]wasmcloud_nats_types.HeaderEntry]
		switch arg7 {
		case 0:

			option4 = witTypes.None[[]wasmcloud_nats_types.HeaderEntry]()
		case 1:
			result := make([]wasmcloud_nats_types.HeaderEntry, 0, arg9)
			for index := 0; index < int(arg9); index++ {
				base := unsafe.Add(unsafe.Pointer(arg8), index*(4*4))
				value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result = append(result, wasmcloud_nats_types.HeaderEntry{value2, value3})
			}

			option4 = witTypes.Some[[]wasmcloud_nats_types.HeaderEntry](result)
		default:
			panic("unreachable")
		}
		witRuntime.Unpin()
		result5 := export_wasmcloud_nats_core_handler.HandleMessage(wasmcloud_nats_types.NatsMessage{value, value0, option, option4})
		var option6 int32
		var option7 uintptr
		var option8 uint32
		switch result5.Tag() {
		case witTypes.ResultOk:

			option6 = int32(0)
			option7 = 0
			option8 = 0
		case witTypes.ResultErr:
			payload := result5.Err()
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)

			option6 = int32(1)
			option7 = uintptr(utf8)
			option8 = uint32(len(payload))
		default:
			panic("unreachable")
		}
		wasm_export_task_return_wasmcloud_nats_core_handler_handle_message(option6, option7, option8)

	}))
}

//go:wasmexport [callback][async-lift]wasmcloud:nats/core-handler@0.1.0#handle-message
func wasm_export_callback_wasmcloud_nats_core_handler_handle_message(event0 uint32, event1 uint32, event2 uint32) uint32 {
	return witAsync.Callback(event0, event1, event2)
}

//go:wasmimport [export]wasmcloud:nats/core-handler@0.1.0 [task-return]handle-message
func wasm_export_task_return_wasmcloud_nats_core_handler_handle_message(arg0 int32, arg1 uintptr, arg2 uint32)
